import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Archax - Application Data Filter',
  description: 'Generated by JKL',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
